package com.nenton.gamesofthrones.data.storage;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nenton.gamesofthrones.data.storage.Aliases;
import com.nenton.gamesofthrones.data.storage.Allegiances;
import com.nenton.gamesofthrones.data.storage.Persons;
import com.nenton.gamesofthrones.data.storage.Titles;
import com.nenton.gamesofthrones.data.storage.TvSeries;

import com.nenton.gamesofthrones.data.storage.AliasesDao;
import com.nenton.gamesofthrones.data.storage.AllegiancesDao;
import com.nenton.gamesofthrones.data.storage.PersonsDao;
import com.nenton.gamesofthrones.data.storage.TitlesDao;
import com.nenton.gamesofthrones.data.storage.TvSeriesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aliasesDaoConfig;
    private final DaoConfig allegiancesDaoConfig;
    private final DaoConfig personsDaoConfig;
    private final DaoConfig titlesDaoConfig;
    private final DaoConfig tvSeriesDaoConfig;

    private final AliasesDao aliasesDao;
    private final AllegiancesDao allegiancesDao;
    private final PersonsDao personsDao;
    private final TitlesDao titlesDao;
    private final TvSeriesDao tvSeriesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aliasesDaoConfig = daoConfigMap.get(AliasesDao.class).clone();
        aliasesDaoConfig.initIdentityScope(type);

        allegiancesDaoConfig = daoConfigMap.get(AllegiancesDao.class).clone();
        allegiancesDaoConfig.initIdentityScope(type);

        personsDaoConfig = daoConfigMap.get(PersonsDao.class).clone();
        personsDaoConfig.initIdentityScope(type);

        titlesDaoConfig = daoConfigMap.get(TitlesDao.class).clone();
        titlesDaoConfig.initIdentityScope(type);

        tvSeriesDaoConfig = daoConfigMap.get(TvSeriesDao.class).clone();
        tvSeriesDaoConfig.initIdentityScope(type);

        aliasesDao = new AliasesDao(aliasesDaoConfig, this);
        allegiancesDao = new AllegiancesDao(allegiancesDaoConfig, this);
        personsDao = new PersonsDao(personsDaoConfig, this);
        titlesDao = new TitlesDao(titlesDaoConfig, this);
        tvSeriesDao = new TvSeriesDao(tvSeriesDaoConfig, this);

        registerDao(Aliases.class, aliasesDao);
        registerDao(Allegiances.class, allegiancesDao);
        registerDao(Persons.class, personsDao);
        registerDao(Titles.class, titlesDao);
        registerDao(TvSeries.class, tvSeriesDao);
    }
    
    public void clear() {
        aliasesDaoConfig.clearIdentityScope();
        allegiancesDaoConfig.clearIdentityScope();
        personsDaoConfig.clearIdentityScope();
        titlesDaoConfig.clearIdentityScope();
        tvSeriesDaoConfig.clearIdentityScope();
    }

    public AliasesDao getAliasesDao() {
        return aliasesDao;
    }

    public AllegiancesDao getAllegiancesDao() {
        return allegiancesDao;
    }

    public PersonsDao getPersonsDao() {
        return personsDao;
    }

    public TitlesDao getTitlesDao() {
        return titlesDao;
    }

    public TvSeriesDao getTvSeriesDao() {
        return tvSeriesDao;
    }

}
